#pragma once
#include <iostream>
#include <windows.h>
#include <conio.h>
#include <cmath>
#include <map>
#include <string>
#include <cstring>
#include <fstream>
#include <vector>
#include <thread>
#include <utility>
#include <algorithm>
#include <variant>
#include <iomanip>
#include <random>
#include <chrono>

#include "exprtk/exprtk.hpp"
